npm install grunt --save
npm install yo --save
npm install bower --save
npm install grunt-cli --save
npm install time-grunt --save
npm install grunt-wiredep --save
npm install karma --save
npm install jit-grunt --save
npm install jshint-stylish --save
npm install autoprefixer-core --save
npm install grunt-spritesmith --save
npm install grunt-usemin --save
npm install grunt-google-cdn --save
npm install grunt-angular-templates --save
npm install grunt-clean --save
npm install grunt-contrib-compass --save
npm install grunt-karma karma-phantomjs-launcher karma-jasmine jasmine-core --save
npm install phantomjs-prebuilt --save
npm install autoprefixer --save
npm install grunt-babel --save
npm install grunt-browser-sync --save
npm install grunt-concurrent --save
npm install grunt-contrib-clean --save
npm install grunt-contrib-concat --save
npm install grunt-contrib-copy --save
npm install grunt-contrib-cssmin --save
npm install grunt-contrib-htmlmin --save
npm install grunt-contrib-imagemin --save
npm install grunt-contrib-uglify --save
npm install grunt-contrib-watch --save
npm install grunt-eslint --save
npm install grunt-filerev --save
npm install grunt-mocha --save
npm install grunt-modernizr --save
npm install grunt-newer --save
npm install grunt-postcss --save
npm install grunt-sass --save
npm install grunt-svgmin --save
npm install grunt-usemin --save
npm install grunt-contrib-connect --save

bower install jquery --save
bower install angularjs --save
bower install bootstrap --save
bower install font-awesome --save
bower install es5-shim --save
bower install json3 --save
bower install html5shiv --save
bower install respondJS --save
bower install googletagmanager --save

bower install angular-resource --save
bower install angular-cookies --save
bower install angular-sanitize --save
bower install animate.css --save
bower install angular-animate --save
bower install angular-touch --save
bower install angular-route --save
bower install angular-mocks --save
bower install angular-scenario --save

find ./ -type d -exec chmod 755 {} \;
